#!/usr/bin/env node
// Generates .opencode/{agents,commands} and .claude/{agents,commands} from
// .factory/{agents,commands}/*.md + .factory/factory.config.json. See
// .factory/README.md. Run `pnpm factory:sync` after editing the source.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import prettier from "prettier";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const factoryDir = join(root, ".factory");
const config = JSON.parse(readFileSync(join(factoryDir, "factory.config.json"), "utf8"));

const GENERATED_NOTICE = (sourcePath) =>
  `<!-- Generated by scripts/factory-sync.mjs from ${sourcePath}. Edit there, not here, then run \`pnpm factory:sync\`. -->\n\n`;

function wrapYamlText(text, indent = "  ", width = 78) {
  const words = text.split(/\s+/);
  const lines = [];
  let line = "";
  for (const word of words) {
    if (line && (indent + line + " " + word).length > width) {
      lines.push(indent + line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) lines.push(indent + line);
  return lines.join("\n");
}

function yamlScalar(key, value) {
  return `${key}:\n${wrapYamlText(value)}`;
}

function readBody(kind, name) {
  return readFileSync(join(factoryDir, kind, `${name}.md`), "utf8").trimEnd() + "\n";
}

function writeGenerated(path, frontmatterLines, sourcePath, body) {
  const content = `---\n${frontmatterLines.join("\n")}\n---\n\n${GENERATED_NOTICE(sourcePath)}${body}`;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

// ---- OpenCode ----

function serializeOpencodePermission(permission) {
  const lines = ["permission:"];
  for (const [key, value] of Object.entries(permission)) {
    if (typeof value === "string") {
      lines.push(`  ${key}: ${value}`);
    } else {
      lines.push(`  ${key}:`);
      for (const [pattern, action] of Object.entries(value)) {
        const quoted = /[*\s]/.test(pattern) || pattern === "*" ? `"${pattern}"` : pattern;
        lines.push(`    ${quoted}: ${action}`);
      }
    }
  }
  return lines;
}

function buildOpencodeAgent(name, spec) {
  const oc = spec.opencode;
  const lines = [yamlScalar("description", spec.description), `mode: ${oc.mode}`, `model: ${oc.model}`];
  if (oc.temperature !== undefined) lines.push(`temperature: ${oc.temperature}`);
  if (oc.steps !== undefined) lines.push(`steps: ${oc.steps}`);
  if (oc.permission) lines.push(...serializeOpencodePermission(oc.permission));
  return lines;
}

function buildOpencodeCommand(name, spec) {
  const oc = spec.opencode;
  return [`description: ${spec.description}`, `agent: ${oc.agent}`, `subtask: ${oc.subtask}`];
}

// ---- Claude Code ----

function buildClaudeAgent(name, spec) {
  const cl = spec.claude;
  const lines = [`name: ${name}`, yamlScalar("description", spec.description), `tools: ${cl.tools}`];
  if (cl.disallowedTools) lines.push(`disallowedTools: ${cl.disallowedTools}`);
  if (cl.model) lines.push(`model: ${cl.model}`);
  if (cl.permissionMode) lines.push(`permissionMode: ${cl.permissionMode}`);
  return lines;
}

function buildClaudeCommand(name, spec) {
  const cl = spec.claude;
  const lines = [`description: ${spec.description}`, `agent: ${cl.agent}`, `context: fork`];
  if (cl["allowed-tools"]) lines.push(`allowed-tools: ${cl["allowed-tools"]}`);
  return lines;
}

async function formatMarkdown(content, path) {
  try {
    return await prettier.format(content, { filepath: path });
  } catch {
    return content; // formatting is best-effort; never block sync on it
  }
}

async function sync({ checkOnly }) {
  const targets = [];

  for (const [name, spec] of Object.entries(config.agents)) {
    const body = readBody("agents", name);
    const sourcePath = `.factory/agents/${name}.md`;
    targets.push({
      path: join(root, ".opencode/agents", `${name}.md`),
      frontmatter: buildOpencodeAgent(name, spec),
      sourcePath,
      body,
    });
    targets.push({
      path: join(root, ".claude/agents", `${name}.md`),
      frontmatter: buildClaudeAgent(name, spec),
      sourcePath,
      body,
    });
  }

  for (const [name, spec] of Object.entries(config.commands)) {
    const body = readBody("commands", name);
    const sourcePath = `.factory/commands/${name}.md`;
    targets.push({
      path: join(root, ".opencode/commands", `${name}.md`),
      frontmatter: buildOpencodeCommand(name, spec),
      sourcePath,
      body,
    });
    targets.push({
      path: join(root, ".claude/commands", `${name}.md`),
      frontmatter: buildClaudeCommand(name, spec),
      sourcePath,
      body,
    });
  }

  let stale = [];
  for (const target of targets) {
    const raw = `---\n${target.frontmatter.join("\n")}\n---\n\n${GENERATED_NOTICE(target.sourcePath)}${target.body}`;
    const content = await formatMarkdown(raw, target.path);
    if (checkOnly) {
      let existing = "";
      try {
        existing = readFileSync(target.path, "utf8");
      } catch {
        // missing entirely counts as stale
      }
      if (existing !== content) stale.push(target.path);
    } else {
      mkdirSync(dirname(target.path), { recursive: true });
      writeFileSync(target.path, content);
      console.log(`wrote ${target.path.replace(root + "/", "")}`);
    }
  }

  if (checkOnly) {
    if (stale.length > 0) {
      console.error("out of date (run `pnpm factory:sync`):");
      for (const path of stale) console.error(`  ${path.replace(root + "/", "")}`);
      process.exit(1);
    }
    console.log("factory sync is up to date");
  }
}

const checkOnly = process.argv.includes("--check");
await sync({ checkOnly });
